spring:
  # 2. Database (PostgreSQL)
  datasource:
    # ğŸ‘ˆ Trá» tá»›i tÃªn service cá»§a Docker
    url: jdbc:postgresql://postgres:5432/coffee_auth_db
    # (Username/Password sáº½ Ä‘Æ°á»£c tiÃªm tá»« docker-compose)

  # 4. Redis
  # 5. RabbitMQ
  rabbitmq:
    host: rabbitmq # ğŸ‘ˆ Trá» tá»›i tÃªn service
  data:
    redis:
      host: redis